### ISSUE TITLE
Hands not showing on title screen well raining

### ISSUE THREAD

**Issue by emeraldsrock101** [QuestCraftPlusPlus/QuestCraft#146] opened 2022-02-26 03:18 UTC
**Describe the bug**
On the title screen when it is raining the player hands do not show but you can see them a little bit if you put your controller close to the headset

**To Reproduce**
1. Wait for it to rain if it isn't already
2. See if it happens

**Expected behavior**
A clear and concise description of what you expected to happen. Minecraft hands not showing

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [Quest_2]
 - QuestCraft Version [v1.1.0]

**Additional context**

**Comment by Mage-Enderman** [comment] 2022-02-26 03:31
Temp fix for the hands
https://www.curseforge.com/minecraft/mc-mods/no-weather-effects

**Comment by AirplaneBoi** [comment] 2022-02-26 19:42
Hands in inventory and the crossbar during gameplay don't render while raining either. #

**Comment by ATXLtheAxolotl** [comment] 2022-02-27 14:24
Another duplicate of #83

**Comment by Mage-Enderman** [comment] 2022-02-28 04:14
> Temp fix for the hands https://www.curseforge.com/minecraft/mc-mods/no-weather-effects Or if you're fine with the other artifacts you can change the video settings to Fast or Fancy

I've been introduced to https://www.curseforge.com/minecraft/mc-mods/particle-rain
If you'd still like rain to exist

**Closed** 2022-02-28 17:48 UTC
Labels: bug
