### ISSUE TITLE
[FEATURE] Ability To Swim In Water / Lava With A Swimming Motion With Your Hands

### ISSUE THREAD

**Issue by strohobama** [QuestCraftPlusPlus/QuestCraft#199] opened 2022-03-08 04:42 UTC
instead of swimming with your joystick, you should be able to swim with your hands as well. like if you were wanting to swim up, you would just do it if you were to do it in real life, or if you are just above the water and you want to get to a island via swimming you can just swim like in real life

**Comment by ATXLtheAxolotl** [comment] 2022-03-08 11:16
Duplicate of #64

**Closed** 2022-03-09 13:44 UTC
Labels: feature
