### ISSUE TITLE
[BUG] Game crashes upon signing in

### ISSUE THREAD

**Issue by gyattgyattrizzler** [QuestCraftPlusPlus/QuestCraft#609] opened 2024-07-03 23:46 UTC
### 🤔 Current Behavior

I've tried the side quest version, the GitHub version, and previous versions, and every time I sign in my game crashes. I've never had this problem in the past, only with the latest update.

### ✅ Expected Behavior

I expected to log in and have it work, as I have not had problems in the past.

### 🥽 Headset Details

Meta Quest 2
V66
Questcraft 5.0.0 (Latest)

**Comment by innocentiv** [comment] 2024-07-19 12:16
I encounter the same bug. After linking is confirmed application crash

**Comment by RedstoneFuture** [comment] 2024-07-19 13:26
> I encounter the same bug. After linking is confirmed application crash

Will the verified / linked Microsoft account still be usable after the restart?
With updated VR, updated SideQuest, updated Questcraft and stabile internet connection?

**Comment by innocentiv** [comment] 2024-07-19 13:39
I am using Meta Quest 3 last version. Sideloaded game using SideQuest. Game show Version 5.0.0 RC5 in the launcher. After crash I see the signin button again. The game crash some seconds after the flow on microsoft.com/link is completed ("Done - you can now close this window"). The internet connection is stable. I just tried a login on my local computer using the official Minecraft launcher and Microsoft account and it works fine.

**Comment by innocentiv** [comment] 2024-07-19 13:51
Ok, I checked the log. The issue is username is not set for java version.
Fixed the issue by going to https://www.minecraft.net/en-us/msaprofile/mygames/editprofile and set the profile name for java version

**Comment by RedstoneFuture** [comment] 2024-07-19 13:59
> Ok, I checked the log. The issue is username is not set for java version. Fixed the issue by going to https://www.minecraft.net/en-us/msaprofile/mygames/editprofile and set the profile name for java version.

So it was a new Minecraft account with the Java name not yet defined, right?

**Comment by gyattgyattrizzler** [comment] 2024-07-19 14:02
> > Ok, I checked the log. The issue is username is not set for java version. Fixed the issue by going to https://www.minecraft.net/en-us/msaprofile/mygames/editprofile and set the profile name for java version.
> 
> So it was a new Minecraft account with the Java name not yet defined, right?

The issue for him was that his username wasn't defined, but mine is, and it used to work on questcraft fine up until now.

**Comment by innocentiv** [comment] 2024-07-19 14:30
> > > Ok, I checked the log. The issue is username is not set for java version. Fixed the issue by going to https://www.minecraft.net/en-us/msaprofile/mygames/editprofile and set the profile name for java version.
> > 
> > 
> > So it was a new Minecraft account with the Java name not yet defined, right?
> 
> The issue for him was that his username wasn't defined, but mine is, and it used to work on questcraft fine up until now.

you could share the log Url under "needs help" button, so that we can figure out what the issue is.

**Closed** 2024-08-20 15:04 UTC
Labels: bug

**Comment by MikeRooticalRoots** [comment] 2025-02-09 22:25
Can someone please do a quick tutorial on how to “ set the profile name for java version.”
Please I can’t see any settings for it in the link provided 
Thanks in advance
