### ISSUE TITLE
[FEATURE] smooth turning and keybinds

### ISSUE THREAD

**Issue by Rickeyrabbit** [QuestCraftPlusPlus/QuestCraft#293] opened 2022-04-22 03:18 UTC
Basically I'd like to suggest smooth turning as an option alongside snap turning, and some kind of way to use keybinds, any mod which has keybinds is almost unusable at the moment. By the way what you guys have done here with this, running pc vr minecraft on an android platform in a way that's actually playable, it's a technical marvel, good job guys, just wow.

**Comment by Flopgop** [comment] 2022-09-08 21:05
Dupe of #383

**Closed by Flopgop** 2022-09-08 21:05 UTC
Labels: feature
