### ISSUE TITLE
 [BUG] bow has incorrect accuracy

### ISSUE THREAD

**Issue by isseithegod** [QuestCraftPlusPlus/QuestCraft#393] opened 2022-09-13 08:55 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Headset Details (please complete the following information):**
 - Quest Build: [e.g. v37.0]
 - Device: [e.g. Quest_1, Quest_2]
 - QuestCraft Version [e.g. v1.2.3]

**Additional context**

**Comment by Flopgop** [comment] 2022-09-13 08:56
Dupe of #372

**Closed by Flopgop** 2022-09-13 08:56 UTC
Labels: bug

**Comment by isseithegod** [comment] 2022-09-13 10:06
> Dupe of #372

oop sorry didn't see it
