### ISSUE TITLE
[BUG] Game crashes out after entering Multiplayer Server details

### ISSUE THREAD

**Issue by slavdok** [QuestCraftPlusPlus/QuestCraft#634] opened 2024-12-09 15:05 UTC
### 🤔 Current Behavior

When I go to Multiplayer and Add Server, as soon as I finish entering server details and click "Done" the game completely crashes out. It doesn't matter what details are being entered. It crashes the moment "Done" is pressed.

### ✅ Expected Behavior

I except the game to save my server details... and not crash...

### 🥽 Headset Details

Quest Build v71
Quest Device: Quest 3
QuestCraft: 5.0.0

### ℹ️ Anything else?

Using 1.20.4 in-game

**Comment by computer-catt** [comment] 2024-12-09 15:35
this is likely a duplicate if issue https://github.com/QuestCraftPlusPlus/QuestCraft/issues/630
inputs are currently broken due to openxr stuff on facebooks end

**Comment by TruFoox** [comment] 2024-12-09 17:37
That's just an issue with v71.

**Comment by Cartrigger** [comment] 2024-12-10 06:04
Duplicate of #630 and is planned to be fixed in update 5.1.0 public.

**Closed by Cartrigger** 2024-12-10 06:04 UTC
Labels: bug
