### ISSUE TITLE
Grey screen  [BUG]

### ISSUE THREAD

**Issue by Tman564ws1** [QuestCraftPlusPlus/QuestCraft#401] opened 2022-10-12 14:56 UTC
**Describe the bug**
Whenever I click on play, it will say loading and either one three things will happen. 
1It will say you don't have enough ram which I do. It's a 250 gigabyte headset. 
2  It will just be a grey screen and you can't do anything except exit the game. 
3It will go a gray screen And then after a couple seconds it'll bring you back to the sign-in page. 
**To Reproduce**
1. Click on play. 
2. Wait for it to load. 
3. See error

**Expected behavior**
It. Go to the Minecraft home screen. 
Sorry I don't know how to get a screenshot onto this. 

**Headset Details (please complete the following information):**
 - Quest Build: v44
 - Device: Quest_2
 - QuestCraft Version 2.0.1

**Additional context**

**Comment by skdy520** [comment] 2022-10-14 08:24
😭😭😭

**Comment by jifengshandian** [comment] 2022-10-14 17:24
the same situation

**Comment by Rickeyrabbit** [comment] 2022-10-16 06:23
same here too

**Comment by DethDefier** [comment] 2022-10-16 23:35
same

**Comment by rasta420421** [comment] 2022-10-18 01:48
I'm am noticing the same issues. For me, I am noticing when it says I don't have have enough ram it shows how much available ram I have. The available ram can change each time that error occurs.

**Comment by killianh94** [comment] 2022-10-18 10:44
I don't think your quest has 250 GB RAM. I think you mean 250 GB storage space. But RAM and storage space are 2 different things. You have a hard disk where you can store files, the hard disk has e.g. 64, 128, 256 GB or TB etc. The you have your RAM, when you want to play a game, the game stores the data needed temporary into the RAM. "Normal" Computers has about 8 to 16 GB RAM and especially Minecraft is a sort of game which need so much ressources.

**Comment by HamburgerSoftware** [comment] 2022-10-18 22:46
I am in the same boat do we have any updates?

**Comment by Rickeyrabbit** [comment] 2022-10-20 02:45
devs are silent, im on quest v46 having the same issue, the quest app says im not in the ptc

**Comment by Rickeyrabbit** [comment] 2022-10-21 06:07
well alright, i guess thats the end of questcraft

**Comment by DED0026** [comment] 2022-11-02 01:28
@Rickeyrabbit  devs are **not** silent and this is **not** the end of questcraft
questcraft is broken right now because of quest pro updates
they are switching to fabric vivecraft as a mcvr core and probably a in vr application for minecraft
these things take time and if you look in their discord server you can see the progress hope people see this because questcraft is still alive and going its just some updates are breaking questcraft

**Comment by orange7563** [comment] 2022-11-02 02:05
well, the "updates" where we are working on it pretty much

**Comment by orange7563** [comment] 2022-11-03 03:46
and isn't this the same as not entering 3D mode

**Comment by DED0026** [comment] 2022-11-05 00:01
> well, the "updates" where we are working on it pretty much

> and isn't this the same as not entering 3D mode

I will be honest I have no idea what the issue is, the updates are not in the announcements channel. the only announced update is that they are working on it and meta broke something, however the actual frequent progress updates are in #github-updates in the questcraft server. hope this helps, they are working on it.

**Comment by Rickeyrabbit** [comment] 2022-12-11 04:09
> > well, the "updates" where we are working on it pretty much
> 
> > and isn't this the same as not entering 3D mode
> 
> I will be honest I have no idea what the issue is, the updates are not in the announcements channel. the only announced update is that they are working on it and meta broke something, however the actual frequent progress updates are in #github-updates in the questcraft server. hope this helps, they are working on it.
> 
> there are frequently beta builds in the pojavlauncher repo that you can test for fixes, catch with that is you do not get help (its a beta build and stuff is due to change).

ive tried and googled, but i cannot find #github-updates

**Comment by DED0026** [comment] 2022-12-26 10:55
> > > well, the "updates" where we are working on it pretty much
> > 
> > 
> > > and isn't this the same as not entering 3D mode
> > 
> > 
> > I will be honest I have no idea what the issue is, the updates are not in the announcements channel. the only announced update is that they are working on it and meta broke something, however the actual frequent progress updates are in #github-updates in the questcraft server. hope this helps, they are working on it.
> > there are frequently beta builds in the pojavlauncher repo that you can test for fixes, catch with that is you do not get help (its a beta build and stuff is due to change).
> 
> ive tried and googled, but i cannot find #github-updates

github updates was deleted or archived on the server some time before you said this. not to fear the issue has been partially fixed with a public beta

**Closed** 2022-12-27 18:25 UTC
Labels: bug, in progress
