### ISSUE TITLE
[FEATURE] Add a non vr mod so pc players could see your VR movements

### ISSUE THREAD

**Issue by ReyTheDog** [QuestCraftPlusPlus/QuestCraft#326] opened 2022-06-11 07:34 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wellsilver** [comment] 2022-06-11 22:19
QuestCraft uses MCXR Wich does have this, please refer to MCXR

**Comment by Cartrigger** [comment] 2022-06-23 08:05
Soon.

**Comment by StormDragon-64** [comment] 2022-06-26 19:22
Already coming, there is already an image in #dev-chat in the discord

**Comment by Flopgop** [comment] 2022-09-08 20:49
Dupe of #385

**Closed by Flopgop** 2022-09-08 20:49 UTC
Labels: feature
