### ISSUE TITLE
V44 Grey Screen Temporary Fix:

### ISSUE THREAD

**Issue by Bhood23** [QuestCraftPlusPlus/QuestCraft#411] opened 2022-12-25 03:36 UTC
V44 Launch QuestCraft Temporary Fix:

https://www.youtube.com/watch?v=TLWR_3hEBJU

**Comment by Flopgop** [comment] 2022-12-25 03:41
This is already posted on our [discord](https://discord.gg/questcraft) and is being fixed soon, there is no need for this to be an issue. Also dupe of #401

**Closed by Flopgop** 2022-12-25 03:41 UTC
Labels: bug

**Comment by Bhood23** [comment] 2022-12-25 06:02
Sorry didn't know because I have gotten banned from the QuestCraft discord after Someone hacked my account I recovered it but Idk how to get back into QuestCraft Discord ): anyway Sorry

**Comment by wellsilver** [comment] 2022-12-26 00:58
> Sorry didn't know because I have gotten banned from the QuestCraft discord after Someone hacked my account I recovered it but Idk how to get back into QuestCraft Discord ): anyway Sorry

he ligit sent a link for the invite

**Comment by Bhood23** [comment] 2022-12-26 05:27
> > Sorry didn't know because I have gotten banned from the QuestCraft discord after Someone hacked my account I recovered it but Idk how to get back into QuestCraft Discord ): anyway Sorry
> 
> he ligit sent a link for the invite

Lmao I am Banned I know he sent a Invite link but it Banned me because I can join any other server but this one always gives me a Link Expired
![Uploading Screenshot_20221226-152610.png…]()

**Comment by Bhood23** [comment] 2022-12-26 05:28
![Screenshot_20221226-152610](https://user-images.githubusercontent.com/80179069/209506605-e3aa636a-6a3b-4288-b661-53d1902396dd.png)
