### ISSUE TITLE
[FEATURE] Add pointers when typing

### ISSUE THREAD

**Issue by DarkFlame204** [QuestCraftPlusPlus/QuestCraft#266] opened 2022-03-31 22:13 UTC
**Is your feature request related to a problem? Please describe.**
When typing, it is a bit difficult to see where you are typing because there isn’t a pointer.

**Describe the solution you'd like**
A simple white line pointing to where you will type.

**Comment by Flopgop** [comment] 2022-09-08 21:03
Dupe of #302

**Closed by Flopgop** 2022-09-08 21:03 UTC
Labels: feature
