### ISSUE TITLE
[BUG] Cant login with majong account

### ISSUE THREAD

**Issue by Xnitro67** [QuestCraftPlusPlus/QuestCraft#278] opened 2022-04-11 20:39 UTC
there is no button to log in with majong account on latest version

**Comment by parkerlreed** [comment] 2022-04-11 22:32
Yes... You HAVE to use a Microsoft account now. All legit Mojang accounts got months of advanced warning to migrate. 

https://help.minecraft.net/hc/en-us/articles/4403181904525-How-to-Migrate-Your-Mojang-Account-to-a-Microsoft-Account

**Comment by Flopgop** [comment] 2022-09-08 21:00
Won't fix, not a bug.

**Closed** 2022-09-08 21:00 UTC
Labels: bug
