### ISSUE TITLE
[FEATURE] In addition to the colon request, add the "shift" key and all the other remaining special characters in a irl keyboard to the questcraft keyboard

### ISSUE THREAD

**Issue by AirplaneBoi** [QuestCraftPlusPlus/QuestCraft#219] opened 2022-03-18 22:34 UTC
Not a problem, just a minor inconvenience, mainly because I cannot capitalize letters or add certain characters that I would in java Minecraft with a traditional physical keyboard. 

Applies to both quest 1 and 2 

No workaround found

**Comment by IzzyDotExe** [comment] 2022-03-19 15:03
Duplicate of #208

**Closed by IzzyDotExe** 2022-03-19 15:03 UTC
Labels: feature

**Comment by IzzyDotExe** [comment] 2022-03-19 15:04
If you want to add ideas to a feature request, please add a comment to that feature rather than making a new one
