### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by eusfisdf** [QuestCraftPlusPlus/QuestCraft#142] opened 2022-02-25 23:10 UTC
now this isnt really a problem as it is more of a irritating thing to me.

Vive craft has all of the cool irl features like punching, jumping and crouching and i think it would be a very cool thing to add to a standalone version of Minecraft VR

**Comment by IzzyDotExe** [comment] 2022-02-26 20:46
Duplicate of #64 no eta for gestures but it will be added in the future.

**Closed** 2022-02-26 20:47 UTC
Labels: duplicate, feature
