### ISSUE TITLE
[FEATURE]When moving around your inventory slots. You should have a choice to use grip Or a thumbstick. 

### ISSUE THREAD

**Issue by Tman564ws1** [QuestCraftPlusPlus/QuestCraft#344] opened 2022-07-03 20:25 UTC
**Describe the solution you'd like**
I would like when you are in the MCXR Menu that you could choose to Move around your inventory slots using grip or using the thumbstick.

**Comment by CyorgGit** [comment] 2022-07-05 01:44
I agree. Grip should be the default, and for some people that prefer the thumbstick, it could be toggled somewhere in the controls menu.

**Comment by ReubenDollmanYT** [comment] 2022-07-05 01:54
The reason it was changed from grips was that they were broken 
in the next update they should be back to grips

**Comment by Tman564ws1** [comment] 2022-07-06 22:37
ya

**Comment by Flopgop** [comment] 2022-09-08 20:45
Kinda dupe of #383

**Closed by Flopgop** 2022-09-08 20:45 UTC
Labels: feature
