### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by FemFatal** [QuestCraftPlusPlus/QuestCraft#226] opened 2022-03-19 19:20 UTC
Please add smooth turn

**Comment by IzzyDotExe** [comment] 2022-03-21 14:35
duplicate of #119

**Closed by IzzyDotExe** 2022-03-21 14:35 UTC
Labels: feature

**Comment by wellsilver** [comment] 2022-03-23 18:55
They are adding smooth turning, I think it was projected for v1.2 but if it wasnt added it may be added in the future,

in the meantime, ACTUALLY TURN YOUR BODY! Though there will be support added for sitting there is no support for it at the moment
