### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by stereomonke** [QuestCraftPlusPlus/QuestCraft#171] opened 2022-02-27 18:38 UTC
Being able to punch mobs/blocks and deal damage/break the block

**Comment by ATXLtheAxolotl** [comment] 2022-02-27 18:40
Duplicate of #64

**Comment by ATXLtheAxolotl** [comment] 2022-02-27 18:41
Please, please check if this feature has already been requested before making your request.

**Closed** 2022-02-28 13:20 UTC
Labels: feature
