### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GearMaster0000** [QuestCraftPlusPlus/QuestCraft#58] opened 2022-02-22 23:43 UTC
There is an x-ray glitch when you go underwater you can see objects through walls

**Expected behavior**
normal minecraft water

**Screenshots**

**Headset Details (please complete the following information):**
v37.0
Quest_2
v1.2.3

**Additional context**

**Comment by JD-The-65th** [comment] 2022-02-23 05:10
Duplicate of #31

**Comment by ATXLtheAxolotl** [comment] 2022-03-03 12:32
This is a duplicate as mentioned above can this be closed.

**Closed** 2022-03-03 16:44 UTC
Labels: bug
