### ISSUE TITLE
[FEATURE] Add a menu that enables custom keybinds

### ISSUE THREAD

**Issue by TwoKrazy** [QuestCraftPlusPlus/QuestCraft#269] opened 2022-04-03 19:26 UTC
**Is your feature request related to a problem? Please describe.**
There are plenty of keybinds that aren't accessible on the Quest touch controllers simply due to the lack of a sufficient amount of buttons on them.

**Describe the solution you'd like**
A GUI that allows you to press buttons and have them send custom keybinds, kinda like the Quick Chat feature but with individual keys instead of messages. The buttons could be stored in an external file, similar to how the mobile PojavLauncher stores controls in a `<control name>.json` file. This would enable access to nearly any feature in the game, or even mods, since then nearly any keybind/combination can be accessible via this menu.

**Additional context**
![7efbc4378902e779b8b9af996201382c.png](https://user-images.githubusercontent.com/45135693/161444602-f32744c2-5e64-422f-92fe-4b7e52d02584.png) this menu has plenty of space for more buttons

**Comment by Flopgop** [comment] 2022-09-08 21:08
Dupe of #383

**Closed by Flopgop** 2022-09-08 21:08 UTC
Labels: feature

**Comment by TwoKrazy** [comment] 2022-10-12 22:38
> Dupe of #383

bruh this one was made before #383
