### ISSUE TITLE
[FEATURE] mappable controller buttons for things like minimap 

### ISSUE THREAD

**Issue by alexderpyfox** [QuestCraftPlusPlus/QuestCraft#337] opened 2022-06-27 16:49 UTC
**Is your feature request related to a problem? Please describe.**
Yeah so when you have mods like minimap and such you can't currently bind the controller buttons to open it or change the mapping it just doesn't register the controller buttons as a button 

**Describe the solution you'd like**
A way to map buttons 

**Describe alternatives you've considered**
Yeah

**Additional context**
Would be handy too if you want to change button mapping for controlls too

**Comment by Flopgop** [comment] 2022-09-08 20:48
Dupe of #383

**Closed by Flopgop** 2022-09-08 20:48 UTC
Labels: feature
