### ISSUE TITLE
[BUG] If QCXR crashes it refuses to start until headset is restarted

### ISSUE THREAD

**Issue by MasterFoann** [QuestCraftPlusPlus/QuestCraft#433] opened 2022-12-31 01:04 UTC
how to reproduce this bug:

once logged in, hit play. For me, this causes the app to immediately close, returning to home.

If you re-open the app, it will sit at the first loading screen before the "made with unity" screen.

after this you must restart the headset to get back to the main menu

**Comment by MasterFoann** [comment] 2022-12-31 01:05
this is a dupe, whoops

**Comment by thejudge156** [comment] 2022-12-31 18:58
I don't think it is, at least needing the headset to restart. I will leave this open.

**Comment by MrBIO69** [comment] 2023-01-09 15:13
Still an issue. For some reason, it doesn't say anything in latestlog.txt.

**Comment by thejudge156** [comment] 2023-02-10 02:47
Confirmed, I was confused in Dec because I forgot that the process doesn't actually die when the home button is pressed during XR Load, will look into.

**Comment by thejudge156** [comment] 2023-06-15 04:29
This is probably fixed by now lol

**Closed by thejudge156** 2023-06-15 04:29 UTC
Labels: bug
