### ISSUE TITLE
[FEATURE] Button to move

### ISSUE THREAD

**Issue by Rolandsan04** [QuestCraftPlusPlus/QuestCraft#379] opened 2022-08-22 19:47 UTC
**Is your feature request related to a problem? Please describe.**
Can Button to move can be optional to replace teleport I have a drifty controller and Teleport does not work on servers

**Describe the solution you'd like**
Button to move replacing teleport

**Describe alternatives you've considered**

**Additional context**
So drifty controller players can play servers

**Comment by Manguyyesno332** [comment] 2022-08-22 23:39
it would probably just be better if you could set custom control binding

**Comment by thejudge156** [comment] 2022-09-02 22:06
Limitation of OpenXR

Sorenon is working on a remapping layer rn

**Comment by Flopgop** [comment] 2022-09-08 20:37
Somewhat a dupe of #383

**Closed by Flopgop** 2022-09-08 20:37 UTC
Labels: feature
