### ISSUE TITLE
[BUG] When it rains, crosshair goes away.

### ISSUE THREAD

**Issue by CitruFruit** [QuestCraftPlusPlus/QuestCraft#162] opened 2022-02-27 02:10 UTC
**Describe the bug**
Whenever there  is any rain at all, the crosshair will go away. 

**To Reproduce**
1. Join a world
2. Wait for it to rain
3. (Possibly not necessary) Open Inventory

**Expected behavior**
It is expected for the crosshair to disappear

**Screenshots**
[https://imgur.com/a/n0zMcIz](https://imgur.com/a/n0zMcIz)

**Headset Details (please complete the following information):**
 - Quest Build: v37.0
 - Device: Quest_2
 - QuestCraft Version 1.1.1

**Additional context**
I don't usually notice when it happens for a bit, and I open my inventory often so it could be related to it raining and opening a menu as well.

**Comment by ReubenDollmanYT** [comment] 2022-02-27 09:59
This is allready knowen / check common issues / bugs / faq

**Comment by ATXLtheAxolotl** [comment] 2022-02-27 14:22
Duplicate of #83

**Comment by Mage-Enderman** [comment] 2022-02-28 04:14
https://www.curseforge.com/minecraft/mc-mods/noweather
OR if you'd prefer to replace rain to fix weird issues cause by it
https://www.curseforge.com/minecraft/mc-mods/particle-rain
Also adds windy sand/sandstorms to deserts

**Closed** 2022-02-28 17:48 UTC
Labels: bug
