### ISSUE TITLE
[BUG] Cobblemon Crashes

### ISSUE THREAD

**Issue by SyeGD** [QuestCraftPlusPlus/QuestCraft#500] opened 2023-04-30 00:43 UTC
### 🤔 Current Behavior

My game crashes with the Cobblemon Fabric mod installed.
I got it with the Modmanager.

### ✅ Expected Behavior

I expect it to open Minecraft with Cobblemon installed. It doesn't. I will update this if trying to install it without the modmanager would work.

### 🥽 Headset Details

Quest 2
Questcraft v4.0

### ℹ️ Anything else?

a mcdouble.

**Comment by Flopgop** [comment] 2023-04-30 00:44
Please provide logs

**Comment by SyeGD** [comment] 2023-04-30 01:44
I don't think it has logs.

**Comment by SyeGD** [comment] 2023-04-30 01:47
It just crashes with no warning whatsoever.

**Comment by SyeGD** [comment] 2023-04-30 02:01
Tried the MCVR API. Didn't work.

**Comment by AbyssVoid205** [comment] 2023-04-30 20:23
![com qcxr qcxr-20230430-130345](https://user-images.githubusercontent.com/132178183/235374632-fe00fd4d-a557-4444-afd8-921c78f111d7.jpg)

**Comment by AbyssVoid205** [comment] 2023-04-30 20:25
but when loading a world it gets half way and crashes saying not enough memory

**Comment by thejudge156** [comment] 2023-06-15 20:49
Duplicate of #520

**Closed by thejudge156** 2023-06-15 20:49 UTC
Labels: bug
