### ISSUE TITLE
[BUG] Immersive Controls for breaking blocks dont work properly

### ISSUE THREAD

**Issue by Manguyyesno332** [QuestCraftPlusPlus/QuestCraft#373] opened 2022-08-19 23:19 UTC
Im not sure if this is just a bug because the 2.0 early build but in questcraft 2.0 hitting mobs is fine but breaking blocks is really annoying and i would like it if it was more like vivecraft because i have to nonstop break a block and it takes me like 30 seconds just to break a piece of dirt. it would be nice if it was like vivecraft where it gives you like 10 seconds to react and the faster you did it the faster it broke and vice versa

Headset: Meta quest 2 (v43)
Version: 2.0 Unfinished build

if anyone knows if this is just an issue apart of the unfinished build then tell me because breaking things with immersive controls is really annoying.

**Comment by Flopgop** [comment] 2022-09-08 20:39
This is working as intended but we might be able to add a delay between when you stop breaking the block and when the block loses it's breaking progress.

**Comment by Manguyyesno332** [comment] 2022-09-09 16:24
Ok.

**Comment by thejudge156** [comment] 2022-09-16 15:50
Will be included in the new VR mod

**Closed by thejudge156** 2022-09-16 15:50 UTC
Labels: bug, looking into it

**Comment by Manguyyesno332** [comment] 2022-09-21 09:58
alright
