### ISSUE TITLE
[BUG] the game renders it weird, if i see thru glass/water i can see caves like with xray

### ISSUE THREAD

**Issue by fischerbootii** [QuestCraftPlusPlus/QuestCraft#47] opened 2022-02-22 19:52 UTC
**Describe the bug**
When i look on glass with a block behind/water with a block behind, i can see thru the world.
**To Reproduce**
1. Played on Hypixel/Any other Server
2. Look thru glass.
3. you can see thru it like with xray.

**Expected behavior**
See the normal block under glass/water

**Screenshots**
*dont have any 

**Headset Details (please complete the following information):**
 - Quest Build: Idk
 - Device: Quest 2
 - QuestCraft Version First Release
 

How can i fix it?

**Comment by ATXLtheAxolotl** [comment] 2022-02-22 19:57
Duplicate of #31

**Comment by fischerbootii** [comment] 2022-02-22 19:58
Didnt see that

**Closed** 2022-03-03 16:45 UTC
Labels: bug
