### ISSUE TITLE
[FEATURE] Ideas

### ISSUE THREAD

**Issue by icedRyan67** [QuestCraftPlusPlus/QuestCraft#159] opened 2022-02-26 23:52 UTC
I think there should be an easier way to set keybinds like combinations to say bring up chat or drop an item. Another idea if im trying to type a server or be in chat there should be a button that says keyboard simular to the Oculus keyboard.

**Comment by ATXLtheAxolotl** [comment] 2022-02-27 17:13
Duplicate of #56 and #90

**Closed** 2022-02-27 17:25 UTC
Labels: feature
