### ISSUE TITLE
[FEATURE] physical collisions/control settings

### ISSUE THREAD

**Issue by FoxOffice** [QuestCraftPlusPlus/QuestCraft#87] opened 2022-02-23 16:23 UTC
**Is your feature request related to a problem? Please describe.**
it is related to the issue of turning

**Describe the solution you'd like**
Earlier it was stated things such as rapidly hitting blocks to break them and swinging swords to attack would be implemented in a reddit post about 9 months ago. I just want to know progress on this feature and i figure this is related to control settings so i figured i'd bring up snap and smooth turn. it would be really nice to be able to change between snap and smooth turn and adjust sensitivity.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Only have moving your arms apply to attacks and not breaking blocks would probably be just as good.

**Additional context**
Add any other context or screenshots about the feature request here. Reddit post mentioned was this 

https://www.google.com/url?q=https://www.reddit.com/r/sidequest/comments/nshjos/questcraft_work_in_progress_read_the_damned_faq/&sa=U&ved=2ahUKEwi24on4nZb2AhUoJkQIHbudBzoQFnoECAUQAg&usg=AOvVaw1yBDz9I5T2pdBjZXuMfpt8

**Comment by ATXLtheAxolotl** [comment] 2022-02-23 23:45
This is a duplicate of #64

**Closed** 2022-02-26 20:50 UTC
Labels: feature
