### ISSUE TITLE
Water allows you to see came systems

### ISSUE THREAD

**Issue by MasterNoob0** [QuestCraftPlusPlus/QuestCraft#62] opened 2022-02-22 23:56 UTC
**Describe the bug**
When looking at water from above you can see any cave systems underground 

**To Reproduce**
1. Look at water
2. See caves

**Expected behavior**
To not see caves 
**Screenshots**
![image](https://user-images.githubusercontent.com/69646234/155239709-62a5a523-a1f5-4010-8e2c-78babb45b068.jpeg)
**Headset Details (please complete the following information):**
 - Device: quest 2

**Additional context**

**Comment by ProtatoPlus** [comment] 2022-02-22 23:57
i found a fix: switch graphics to fast you will get a horizon bug but xray with water/glass wont be present so just chose which one you can tolerate.

**Comment by JD-The-65th** [comment] 2022-02-23 00:15
duplicate of #31

**Comment by ATXLtheAxolotl** [comment] 2022-03-03 12:32
This is a duplicate as mentioned above can this be closed.

**Closed** 2022-03-03 16:44 UTC
Labels: bug
