### ISSUE TITLE
[BUG] Not openng

### ISSUE THREAD

**Issue by Parker0808** [QuestCraftPlusPlus/QuestCraft#510] opened 2023-05-03 20:09 UTC
### 🤔 Current Behavior

My game is questcraft
After I hit play and it finishes downloading it exits out of the game and goes to my main home environment and says not enough memory.

### ✅ Expected Behavior

I expected for it to start running quest craft game.

### 🥽 Headset Details

 Quest v51
Oculus Quest 2
QuestCraft version v1.19.4 fabric

**Comment by CrowPixel** [comment] 2023-05-03 20:14
4.0 is currently experiencing memory issues. The devs are actively working to fix this problem, so be patient! 

This doesn't mean Questcraft will not work, you may just need to keep trying until it opens

**Comment by Parker0808** [comment] 2023-05-03 20:15
So its not a problem on my end?

**Comment by DED0026** [comment] 2023-05-04 05:43
> So its not a problem on my end?

it isnt, try another version and if that doesn't work id try a mobile hotspot or different Wi-Fi connection.

**Comment by Parker0808** [comment] 2023-05-04 16:53
I tried a different version and different Wi-Fi connection but it still doesn't work.

**Comment by Parker0808** [comment] 2023-05-11 23:58
I tried using a personal hotspot but it still won’t work. PLZ FIX! CAN’T WAIT TO PLAY WHEN IT ACTUALLY WORKS!!!

**Comment by thejudge156** [comment] 2023-06-15 20:50
Duplicate of #520

**Closed by thejudge156** 2023-06-15 20:50 UTC
Labels: bug
