### ISSUE TITLE
[BUG] Not enough memory

### ISSUE THREAD

**Issue by DethDefier** [QuestCraftPlusPlus/QuestCraft#528] opened 2023-06-13 23:32 UTC
### 🤔 Current Behavior

My game is installed fine, just did a fresh install. I run it, it waits for a bit, and it crashes and says "there is not enough memory to run questcraft"

### ✅ Expected Behavior

The game should probably start.

### 🥽 Headset Details

Quest 2
Questcraft latest release

**Comment by swaggio7** [comment] 2023-06-14 08:02
1. After pressing play, did nothing happen? If so, QuestCraft is installing the MC version you selected. This is an extremely common bug; the best way to overcome this is to keep trying by pressing play again. It may crash a couple of times but still try. You should eventually load it into Minecraft.

**Comment by wellsilver** [comment] 2023-06-14 17:43
There's a memory leak
https://github.com/QuestCraftPlusPlus/QuestCraft/issues/520 (told somewhere here)
It's not questcrafts fault and haved to wait for meta to fix

**Comment by thejudge156** [comment] 2023-06-15 04:33
Duplicate of #520

**Closed by thejudge156** 2023-06-15 04:33 UTC
Labels: bug
