### ISSUE TITLE
[FEATURE] Chat menu for upcoming keyboard

### ISSUE THREAD

**Issue by Kealam** [QuestCraftPlusPlus/QuestCraft#166] opened 2022-02-27 03:52 UTC
**Is your feature request related to a problem? Please describe.**
No, it’s just a feature I think might be nice to have.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. I’d like to use the left oculus button for opening the chat menu, since it’s not being used yet and you guys are implementing a keyboard.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. I couldn’t really think of any other alternatives other than being in a call.

**Additional context**

**Comment by ATXLtheAxolotl** [comment] 2022-02-27 14:27
Duplicate of #90

**Closed** 2022-02-27 17:24 UTC
Labels: feature
