### ISSUE TITLE
[BUG] Aiming with bow

### ISSUE THREAD

**Issue by Rickeyrabbit** [QuestCraftPlusPlus/QuestCraft#299] opened 2022-04-25 01:06 UTC
when aiming with the bow (or any ranged weapon or item) the projectile doesnt go where your crosshair is aiming, but rather it goes where your head is aiming. id like to see my shots be accurate to where im aiming, instead of where im looking, but if due to the nature of the vr hack fixing it isnt possible, might i suggest a crosshair switch for just ranged weapons and items? as in when you pull the bow back, or go to throw a potion, the crosshair switches from a hand controlled direction to a head controlled direction (think gearvr minecraft, where the crosshair is always where youre looking) for the duration of the shot or throw. thanks again for this feat of software engineering guys

**Comment by Flopgop** [comment] 2022-09-08 20:57
Dupe of #372

**Closed by Flopgop** 2022-09-08 20:57 UTC
Labels: bug
